add_newline = false

format = """
$kubernetes$helm$terraform$aws\
$username$hostname$directory\
$git_branch$git_commit$git_state\
$golang$nodejs$lua$docker_context\
$line_break\
$character
"""

##############################
# Global prompt character    #
##############################
[character]
success_symbol = "[âœ](bold green)"

##############################
# Cloud Technologies         #
##############################
[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
style = 'dimmed green'
symbol = "â˜¸ "

[docker_context]
format = 'via [ğŸ‹ $context]($style)'
style = "blue bold"

[helm]
format = 'via ğŸª– [$version](bold white) '

[terraform]
format = '[ğŸğŸ’¨ $version$workspace]($style) '

##############################
# Main row information       #
##############################
[username]
show_always = true
format = '[$user@]($style)'
style_user = 'green'

[hostname]
format = '[$hostname]($style) in '
style = 'green'
ssh_only = false

[directory]
style = 'blue'
home_symbol = "ğŸ  "
truncation_symbol = "ğŸ“‚ "
read_only = ' ï ½'
truncate_to_repo = true

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 12
style = 'dimmed green'

##############################
# Programming languages      #
##############################
[nodejs]
format = 'via [$symbol($version )]($style)'

[lua]
format = 'via [ğŸŒ• $version](bold blue) '

[golang]
format = 'via [ğŸğŸ’¨ $version]($style) '
style = "bold cyan"

[java]
symbol = 'ğŸŒŸ '
